#!/bin/sh 
if [ "$1" = "window" ]
then
	hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -t jpeg -c -q 100 -g - ~/screenshots/$(date +%s).jpeg
fi
if [ "$1" = "fullscreen" ]
then
	grim -t jpeg -c -q 100  ~/screenshots/$(date +%s)-fullscreen.jpeg
fi
